FROM ubuntu:latest

# Installing dependencies and cleaning up
RUN apt-get update && \
        apt-get install -y python3 python3-pip libpq-dev libcurl4-openssl-dev libssl-dev redis-server && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

RUN pip3 install pipenv

WORKDIR /app


COPY Pipfile Pipfile.lock ./
RUN pipenv install --system --deploy

COPY . .

RUN echo "Testing stdout for AWS logging..."

EXPOSE 6379
CMD ["redis-server", "redis.conf", "--bind", "0.0.0.0"]