FROM ubuntu:latest
# Installing dependencies for running a python application
RUN apt-get update && apt-get install -y python3 python3-pip libpq-dev libcurl4-openssl-dev libssl-dev
# Install pipenv
RUN pip3 install pipenv
# Setting the working directory
WORKDIR /app
# Install pipenv dependencies
COPY Pipfile Pipfile.lock ./
RUN pipenv install --system --deploy
# Copying our application into the container
COPY . .
# Running our application
EXPOSE 6400
ENTRYPOINT ["bin/docker-entrypoint"]
CMD ["serve"]